-- INCLASS seed data
TRUNCATE subjects, tutors, testimonials RESTART IDENTITY;

INSERT INTO subjects (slug, name, icon, category, learners, tutors_count, popular, sort_order) VALUES
  ('mathematiques', 'Mathématiques', 'math', 'Scientifique', 21400, 1840, true, 1),
  ('physique-chimie', 'Physique-Chimie', 'physics', 'Scientifique', 14800, 1120, true, 2),
  ('francais', 'Français', 'french', 'Langues', 18300, 1460, true, 3),
  ('anglais', 'Anglais', 'english', 'Langues', 16250, 1310, true, 4),
  ('arabe', 'Arabe', 'arabic', 'Langues', 9400, 870, true, 5),
  ('svt', 'SVT', 'biology', 'Scientifique', 7600, 640, true, 6),
  ('informatique', 'Informatique & Code', 'code', 'Numérique', 5200, 410, true, 7),
  ('soutien-primaire', 'Soutien primaire', 'primary', 'Scolaire', 11900, 980, true, 8),
  ('economie-gestion', 'Économie & Gestion', 'economics', 'Supérieur', 4300, 320, false, 9),
  ('histoire-geo', 'Histoire-Géographie', 'history', 'Littéraire', 3800, 290, false, 10),
  ('philosophie', 'Philosophie', 'philosophy', 'Littéraire', 3100, 210, false, 11),
  ('espagnol', 'Espagnol', 'spanish', 'Langues', 2900, 240, false, 12);

INSERT INTO tutors (slug, full_name, headline, bio, city, subject_slug, subject_label, levels, languages, mode, price_per_hour, rating, reviews, lessons, verified, initials) VALUES
  ('mehdi-alaoui', 'Mehdi A.', 'Ingénieur EMI · 8 ans d''expérience en maths Bac & prépa', 'Méthode par objectifs : diagnostic initial, fiches de cours, exercices types examen et corrections détaillées. Spécialiste du programme national et de la mission française.', 'Casablanca', 'mathematiques', 'Mathématiques', '1ère Bac · 2ème Bac · Prépa', 'Arabe · Français', 'both', 180, '4.9', 214, 1890, true, 'MA'),
  ('sara-haddadi', 'Sara H.', 'Professeure agrégée de français, spécialiste des oraux', 'Expression écrite, méthodologie du commentaire et confiance à l''oral. Chaque séance se termine par un mini-exercice corrigé.', 'Rabat', 'francais', 'Français', 'Collège · Lycée', 'Français · Anglais', 'online', 150, '5.0', 132, 940, true, 'SH'),
  ('omar-benkirane', 'Omar B.', 'Docteur en physique · pédagogie expérimentale', 'Comprendre avant d''appliquer : chaque notion part d''une expérience concrète, puis d''exercices progressifs.', 'Marrakech', 'physique-chimie', 'Physique-Chimie', 'Lycée · Supérieur', 'Arabe · Français · Anglais', 'home', 200, '4.8', 98, 720, true, 'OB'),
  ('hajar-zouiten', 'Hajar Z.', 'Coach anglais IELTS/TOEFL · certifiée Cambridge', 'Conversation dès le premier cours, préparation ciblée aux tests internationaux et vocabulaire académique.', 'Tanger', 'anglais', 'Anglais', 'Lycée · Adultes', 'Anglais · Français', 'online', 160, '4.9', 176, 1320, true, 'HZ'),
  ('anas-tazi', 'Anas T.', 'Développeur senior · Python, algorithmique et projets', 'Du premier script au projet déployé. Cours adaptés aux lycéens en NSI comme aux étudiants en école d''ingénieurs.', 'Casablanca', 'informatique', 'Informatique & Code', 'Lycée · Supérieur · Adultes', 'Français · Anglais', 'online', 220, '4.9', 87, 560, true, 'AT'),
  ('fatima-ezzahra-mounir', 'Fatima Ezzahra M.', 'Institutrice · soutien primaire et méthodologie', 'Lecture, calcul et confiance en soi, avec des séances ludiques de 45 minutes et un point hebdomadaire avec les parents.', 'Fès', 'soutien-primaire', 'Soutien primaire', 'Primaire', 'Arabe · Français', 'home', 110, '5.0', 143, 1010, true, 'FM'),
  ('khalid-rachidi', 'Khalid R.', 'Professeur de SVT · préparation concours médecine', 'Fiches de synthèse, QCM chronométrés et suivi hebdomadaire des annales.', 'Agadir', 'svt', 'SVT', '2ème Bac · Concours', 'Arabe · Français', 'both', 170, '4.8', 64, 430, true, 'KR'),
  ('loubna-saidi', 'Loubna S.', 'Professeure d''arabe · grammaire et expression', 'Approche vivante de la langue arabe : lecture, nahw et rédaction, du collège au niveau avancé.', 'Meknès', 'arabe', 'Arabe', 'Primaire · Collège · Lycée', 'Arabe · Français', 'both', 120, '4.9', 71, 505, true, 'LS'),
  ('younes-fassi', 'Younes F.', 'Prof de maths · spécialiste du régional 1ère Bac', 'Reprise des bases puis entraînement intensif sur les annales régionales et nationales.', 'Rabat', 'mathematiques', 'Mathématiques', 'Collège · 1ère Bac', 'Arabe · Français', 'both', 140, '4.7', 58, 380, true, 'YF'),
  ('imane-belkadi', 'Imane B.', 'Professeure de physique-chimie · mission française', 'Programme français et marocain, préparation aux DS et au Bac avec exercices type sujets.', 'Casablanca', 'physique-chimie', 'Physique-Chimie', 'Collège · Lycée', 'Français', 'online', 175, '4.9', 112, 810, true, 'IB'),
  ('zakaria-oulad', 'Zakaria O.', 'Économie & gestion · étudiants ENCG et FSJES', 'Comptabilité, micro/macro et méthodologie des dissertations économiques.', 'Marrakech', 'economie-gestion', 'Économie & Gestion', 'Bac · Supérieur', 'Arabe · Français', 'online', 165, '4.8', 46, 290, true, 'ZO'),
  ('nadia-lamrani', 'Nadia L.', 'Professeure de SVT et biologie · 12 ans d''expérience', 'Schémas, cartes mentales et méthodologie pour retenir durablement le programme.', 'Tanger', 'svt', 'SVT', 'Collège · Lycée', 'Arabe · Français', 'home', 145, '5.0', 89, 640, true, 'NL'),
  ('samir-ghazi', 'Samir G.', 'Prof d''anglais business & conversation', 'Anglais professionnel, entretiens et prise de parole. Séances 100 % en anglais dès le niveau B1.', 'Casablanca', 'anglais', 'Anglais', 'Adultes · Supérieur', 'Anglais · Français · Arabe', 'online', 190, '4.8', 73, 470, true, 'SG'),
  ('meryem-chraibi', 'Meryem C.', 'Philosophie · méthode de dissertation Bac', 'Construction de problématique, plan et références. Corrections écrites détaillées entre les séances.', 'Rabat', 'philosophie', 'Philosophie', '2ème Bac', 'Français · Arabe', 'online', 130, '4.7', 39, 210, true, 'MC'),
  ('rachid-elkhattabi', 'Rachid E.', 'Histoire-géo · programme national et international', 'Chronologies claires, cartes commentées et entraînement aux épreuves.', 'Oujda', 'histoire-geo', 'Histoire-Géographie', 'Collège · Lycée', 'Arabe · Français', 'both', 115, '4.6', 31, 180, true, 'RE'),
  ('salma-idrissi', 'Salma I.', 'Soutien primaire & CE1-CM2 · pédagogie Montessori', 'Apprentissages ludiques, lecture fluide et autonomie dans les devoirs.', 'Casablanca', 'soutien-primaire', 'Soutien primaire', 'Primaire', 'Français · Arabe', 'home', 100, '4.9', 96, 700, true, 'SI'),
  ('hamza-bennis', 'Hamza B.', 'Espagnol · DELE et conversation', 'Immersion progressive, grammaire simplifiée et préparation aux certifications DELE.', 'Tétouan', 'espagnol', 'Espagnol', 'Lycée · Adultes', 'Espagnol · Français · Arabe', 'online', 125, '4.8', 42, 260, true, 'HB'),
  ('kenza-amrani', 'Kenza A.', 'Développement web · React, JavaScript et projets étudiants', 'Accompagnement sur les projets de fin d''études et bases solides du développement web.', 'Kénitra', 'informatique', 'Informatique & Code', 'Supérieur · Adultes', 'Français · Anglais', 'online', 240, '5.0', 54, 320, true, 'KA');

INSERT INTO testimonials (author_name, author_role, city, quote, detail, rating, sort_order) VALUES
  ('Salma B.', 'student', 'Casablanca', 'J''étais à 8/20 en maths en 1ère Bac. Après 4 mois avec mon prof INCLASS, j''ai eu 15,5 au régional. Il m''explique jusqu''à ce que je comprenne vraiment.', 'Mathématiques · 2ème Bac SM', 5, 1),
  ('Youssef E.', 'parent', 'Rabat', 'Ce que j''apprécie, c''est le compte rendu après chaque séance. Je sais exactement ce que mon fils a travaillé et où il bloque encore.', 'Parent d''un élève de 6ème année', 5, 2),
  ('Nadia L.', 'tutor', 'Marrakech', 'En 6 mois sur INCLASS j''ai construit un planning de 18 heures par semaine. Les paiements arrivent à l''heure et je choisis mes élèves.', 'Professeure de physique-chimie', 5, 3),
  ('Imane K.', 'student', 'Tanger', 'Les cours en ligne le soir m''ont sauvée pendant la prépa. Zéro déplacement et un prof d''anglais qui m''a fait passer le TOEFL à 98.', 'Anglais · Préparation TOEFL', 5, 4),
  ('Karim Z.', 'parent', 'Agadir', 'Deux profs testés, le bon trouvé du premier coup pour ma fille. Le remplacement gratuit après le premier cours, ça change tout.', 'Parent d''une élève de 2ème Bac', 5, 5);
TRUNCATE articles RESTART IDENTITY;
INSERT INTO articles (slug, title, excerpt, category, audience, author, read_minutes, cover, featured, published_at) VALUES
 ('reussir-le-bac-national-plan-revision','Réussir le Bac national : le plan de révision des 12 dernières semaines','Un rétroplanning réaliste, matière par matière, pour aborder le national sans paniquer et sans sacrifier ton sommeil.','Examens','student','Sara H., professeure agrégée',8,'/images/hero-student.jpg',true,'2026-01-12'),
 ('choisir-un-prof-particulier-au-maroc','Comment choisir un prof particulier au Maroc : 7 critères qui comptent vraiment','Diplôme, expérience, feeling, tarif : le guide pour les parents qui veulent éviter les mauvaises surprises.','Parents','parent','Équipe INCLASS',6,'/images/parents.jpg',true,'2026-01-05'),
 ('fixer-son-tarif-horaire-prof-particulier','Professeurs : comment fixer un tarif horaire juste (et le défendre)','Grille de prix par matière, par ville et par niveau, plus la méthode pour augmenter sans perdre tes élèves.','Professeurs','tutor','Amine M., Head of Tutors',7,'/images/become-tutor.jpg',false,'2025-12-18'),
 ('methode-pomodoro-lyceens','La méthode Pomodoro adaptée aux lycéens marocains','25 minutes de travail, 5 de pause : comment structurer une soirée de révision efficace après une journée de cours.','Méthodologie','student','Équipe INCLASS',5,'/images/banner-resources.jpg',false,'2025-12-02'),
 ('apres-le-bac-filieres-marocaines','Après le Bac : panorama des filières marocaines et de leurs concours','CPGE, ENCG, médecine, ENSA, facultés : ce qu''il faut préparer dès la 1ère Bac pour ne rien rater.','Orientation','student','Soukaina L., cofondatrice',10,'/images/lesson-home.jpg',false,'2025-11-20'),
 ('suivre-progres-enfant-sans-pression','Suivre les progrès de son enfant sans mettre la pression','Les 5 indicateurs à regarder chaque mois, et les phrases à éviter avant un contrôle important.','Parents','parent','Hind N., support familles',6,'/images/hero-tutor.jpg',false,'2025-11-04'),
 ('cours-en-ligne-vs-domicile','Cours en ligne ou à domicile : que choisir pour son enfant ?','Coût, logistique, concentration, suivi : comparatif honnête des deux formats les plus demandés au Maroc.','Parents','parent','Équipe INCLASS',5,'/images/lesson-home.jpg',false,'2025-10-15'),
 ('premiere-seance-prof-checklist','Professeurs : la checklist de la première séance réussie','Diagnostic, objectifs, cadre et devoirs : le déroulé qui fait revenir 9 élèves sur 10.','Professeurs','tutor','Amine M., Head of Tutors',6,'/images/become-tutor.jpg',false,'2025-10-02');
